name: Deploy static site + Gamma decks
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Gamma decks from /slides
        if: ${{ secrets.GAMMA_API_KEY != '' }}
        env:
          GAMMA_API_KEY: ${{ secrets.GAMMA_API_KEY }}
        run: node scripts/gamma_generate.js || true

      - name: Build dist
        run: |
          set -e
          rm -rf dist
          mkdir -p dist
          find . -maxdepth 1 -type f -name '*.html' -print0 | xargs -0 -I{} cp -a {} dist/
          for d in assets apps downloads scripts slides batches; do
            [ -d "$d" ] && cp -a "$d" dist/
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
