name: Deploy static site + Gamma decks
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node 20 (fetch built-in) for the generator script
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Run Gamma generator ONLY if the secret exists (guarded inside bash)
      - name: Generate Gamma decks from /slides (optional)
        run: |
          if [ -n "${{ secrets.GAMMA_API_KEY }}" ]; then
            echo "Gamma key present; generating decks…"
            GAMMA_API_KEY='${{ secrets.GAMMA_API_KEY }}' node scripts/gamma_generate.js
          else
            echo "No GAMMA_API_KEY set; skipping Gamma generation."
          fi

      # Build static site into dist/
      - name: Build dist
        run: |
          set -e
          rm -rf dist
          mkdir -p dist
          # copy ALL top-level HTML files
          find . -maxdepth 1 -type f -name '*.html' -print0 | xargs -0 -I{} cp -a {} dist/
          # copy common folders if present
          for d in assets apps downloads scripts slides batches; do
            [ -d "$d" ] && cp -a "$d" dist/
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
